name = "portfolio-unykorn"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# KV namespace — diligence access tokens
[[kv_namespaces]]
binding    = "DILIGENCE_TOKENS"
id         = "8b38004ba58f412dbab99c7e192a4dd5"
preview_id = "646cb6c3af8b4147911f668cb2027b3e"
